### ISSUE TITLE
dbacl table full, some tokens ignored

### ISSUE THREAD

**Issue by GuillaumeSeren** [afewmail/afew#137]
Since a few weeks I have been running into this error
```
Traceback (most recent call last):
  File "/home/gseren/.local/bin/afew", line 11, in <module>
    load_entry_point('afew==1.0.0', 'console_scripts', 'afew')()
  File "/home/gseren/.local/lib64/python3.4/site-packages/afew-1.0.0-py3.4.egg/afew/commands.py", line 205, in main
    inner_main(args, database, query_string)
  File "/home/gseren/.local/lib64/python3.4/site-packages/afew-1.0.0-py3.4.egg/afew/main.py", line 67, in main
    all_messages[:options.reference_set_size]
  File "/home/gseren/.local/lib64/python3.4/site-packages/afew-1.0.0-py3.4.egg/afew/DBACL.py", line 87, in learn
    raise BackendError('dbacl learning failed:\n%s' % process.stderr.read())
afew.DBACL.BackendError: dbacl learning failed:
b'dbacl:warning: table full, some tokens ignored - try with option -h 16\ndbacl:error: the file /home/gseren/.local/share/afew/categories/reference_category is already used for something, use another filename. Nothing written.\n'
```

**Comment by GuillaumeSeren** [comment]
After checking a bit more the file was empty, so removed it, and now the error is gone,
do we need to add a check for that case ?
```
ls -lah /home/gseren/.local/share/afew/categories/reference_category
-rw-r----- 1 gseren gseren 0 Mar 24 13:44 /home/gseren/.local/share/afew/categories/reference_category
rm /home/gseren/.local/share/afew/categories/reference_category
afew -U                                                                                                                                                                                                                   
```
