### ISSUE TITLE
Uncaught XapianError when afew is passed a bad query

### ISSUE THREAD

**Issue by dcbaker** [afewmail/afew#168]
I had a typo in my call to afew today `afew --tag date:yeserday..today`, (note the missing `t`), and I get a traceback:

```txt
Traceback (most recent call last):
  File "/usr/sbin/afew", line 11, in <module>
    load_entry_point('afew==1.2.1.dev1+g3a7e02b', 'console_scripts', 'afew')()
  File "/usr/lib/python3.6/site-packages/afew/commands.py", line 173, in main
    inner_main(args, database, query_string)
  File "/usr/lib/python3.6/site-packages/afew/main.py", line 36, in main
    filter_.run(query_string)
  File "/usr/lib/python3.6/site-packages/afew/filters/BaseFilter.py", line 72, in run
    for message in self.database.get_messages(query):
  File "/usr/lib/python3.6/site-packages/afew/Database.py", line 106, in get_messages
    for message in self.do_query(query).search_messages():
  File "/usr/lib/python3.6/site-packages/notmuch/query.py", line 182, in search_messages
    raise NotmuchError(status)
notmuch.errors.XapianError
```

This should be pretty easy to catch to provide a nicer error message.

**Comment by GuillaumeSeren** [comment]
Hey,
yes it is a good area to add some informative / user features, and PR are open.

Beside that, I think afew output in general, could be better, so if you have ideas / suggestion,
they are welcomed.

**Comment by flokli** [comment]
`notmuch.errors.XapianError` is raised by the `notmuch` python bindings.
I'm not sure whether we should add custom error messages for each possible error `notmuch` bindings can raise. Closing.
