### ISSUE TITLE
Problem with new notmuch version 0.25.2?

### ISSUE THREAD

**Issue by hugoroy** [afewmail/afew#178]
Sorry I can't really make sense out of this:

```
130 hugo@xps ~/.email/afew (git)-[private] % afew --tag --new --verbose     :(
Traceback (most recent call last):
  File "/usr/bin/afew", line 11, in <module>
    load_entry_point('afew==1.2.1.dev22+g6e8e403', 'console_scripts', 'afew')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/afew/commands.py", line 13, in <module>
    from afew.Database import Database
  File "/usr/lib/python3.6/site-packages/afew/Database.py", line 10, in <module>
    import notmuch
  File "/usr/lib/python3.6/site-packages/notmuch/__init__.py", line 54, in <module>
    from .database import Database
  File "/usr/lib/python3.6/site-packages/notmuch/database.py", line 48, in <module>
    class Database(object):
  File "/usr/lib/python3.6/site-packages/notmuch/database.py", line 412, in Database
    _indexopts_set_decrypt_policy = nmlib.notmuch_indexopts_set_decrypt_policy
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libnotmuch.so.5: undefined symbol: notmuch_indexopts_set_decrypt_policy
```

**Comment by hugoroy** [comment]
Okay, that's probably because I have a problem with notmuch python packages on Arch currently...

**Comment by flokli** [comment]
Yeah, looks like your python bindings not matching to the shared library being installed.
