### ISSUE TITLE
Errors during docs build: autodoc: failed to import module u'afew.utils', etc

### ISSUE THREAD

**Issue by yurivict** [afewmail/afew#184]
```
/usr/ports/mail/py-afew/work/afew-1.3.0/docs/source/implementation.rst:11: WARNING: autodoc: failed to import class u'Database' from module u'afew.Database'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named afew.Database
/usr/ports/mail/py-afew/work/afew-1.3.0/docs/source/implementation.rst:18: WARNING: autodoc: failed to import class u'Filter' from module u'afew.Filter'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named afew.Filter
/usr/ports/mail/py-afew/work/afew-1.3.0/docs/source/implementation.rst:24: WARNING: autodoc: failed to import module u'afew.Settings'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named afew.Settings
/usr/ports/mail/py-afew/work/afew-1.3.0/docs/source/implementation.rst:27: WARNING: autodoc: failed to import module u'afew.NotmuchSettings'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named afew.NotmuchSettings
/usr/ports/mail/py-afew/work/afew-1.3.0/docs/source/implementation.rst:34: WARNING: autodoc: failed to import module u'afew.utils'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named afew.utils
```

**Comment by seschwar** [comment]
To provide a bit more detail: This occurs when trying to build the documentation in a clean environment where `afew` isn't already installed.

**Comment by GuillaumeSeren** [comment]
Hey @yurivict @seschwar ,
thank you for the feedback,
that's an issue regarding to the doc generation I am reviewing the patch from @seschwar right now.
