### ISSUE TITLE
Exception in DMARCReportInspectionFilter.py

### ISSUE THREAD

**Issue by matclab** [afewmail/afew#214]
The following exception was raised when running afew:

```
Hook stderr:Traceback (most recent call last):
  File "/usr/bin/afew", line 11, in <module>
    load_entry_point('afew==1.3.0', 'console_scripts', 'afew')()
  File "/usr/lib/python3.7/site-packages/afew/commands.py", line 159, in main
    inner_main(args, database, query_string)
  File "/usr/lib/python3.7/site-packages/afew/main.py", line 23, in main
    filter_.run(query_string)
  File "/usr/lib/python3.7/site-packages/afew/filters/BaseFilter.py", line 60, in run
    self.handle_message(message)
  File "/usr/lib/python3.7/site-packages/afew/filters/DMARCReportInspectionFilter.py", line 115, in handle_message
    auth_results = and_dict(auth_results, read_auth_results(document))
  File "/usr/lib/python3.7/site-packages/afew/filters/DMARCReportInspectionFilter.py", line 83, in read_auth_results
    dkim = auth_results.find('dkim').find('result')
AttributeError: 'NoneType' object has no attribute 'find'

```

**Comment by GuillaumeSeren** [comment]
Hello,
As I don't use this filter myself I can not 100% suree,
but the patch just add a check on `auth_results`,
so let's merge it.

Thank you for the patch.
