### ISSUE TITLE
NullPointerError with HeaderMatchingFilter

### ISSUE THREAD

**Issue by bjesus** [afewmail/afew#253]
Hi, thanks for afew, it's quite an awesome piece of software.

I have my own domain on which I host my email. I'm using mail@mydomain.com for things that are personal, but company@mydomain.com (eg. facebook@mydomain.com , github@mydomain.com ) when I give my email address to companies.

I wrote a simple HeaderMatchingFilter that helps me tag mails based on it, like this:

```
[HeaderMatchingFilter.1]
header = To
pattern = [<| ](?P<user>(?!mail|hi)[A-Za-z0-9._+-]+)@mydomain.com
tags = +{user}

[HeaderMatchingFilter.2]
header = Cc
pattern = [<| ](?P<user>(?!mail|hi)[A-Za-z0-9._+-]+)@mydomain.com
tags = +{user}
```

The idea is to tag mails with the username in the email address.

Everything worked well when I ran it with `--new`, but when running it with `--all` it crashes after quite a short time with this error:

```
DEBUG:afew.filters.HeaderMatchingFilter.HeaderMatchingFilter:Adding tags XXX to id:XXX
Traceback (most recent call last):
  File "/usr/bin/afew", line 11, in <module>
    load_entry_point('afew==2.0.0', 'console_scripts', 'afew')()
  File "/usr/lib/python3.7/site-packages/afew/commands.py", line 160, in main
    inner_main(args, database, query_string)
  File "/usr/lib/python3.7/site-packages/afew/main.py", line 23, in main
    filter_.run(query_string)
  File "/usr/lib/python3.7/site-packages/afew/filters/BaseFilter.py", line 60, in run
    self.handle_message(message)
  File "/usr/lib/python3.7/site-packages/afew/filters/HeaderMatchingFilter.py", line 28, in handle_message
    value = message.get_header(self.header)
  File "/usr/lib/python3.7/site-packages/notmuch/message.py", line 265, in get_header
    raise NullPointerError()
notmuch.errors.NullPointerError
```

I suspect the top `DEBUG` line is actually coming from the message before the failure, because it seems that this message actually gets tagged correctly.

**Comment by andir** [comment]
I am running into the same error. 

In my case it seem to come from the fact that the mail it tries to open doesn't exist at the location report by notmuch.

I have my mails in `/home/andi/Maildir/<account name>` but for some reason notmuch thinks this mail is in `/home/andi/Maildir/<accout name>//home/andi/Maildir`. I have `/home/andi/Maildir` set as prefix directory for all my mails in the `notmuchrc`.

I simply ran the `notmuch search --output=messages $filter | grep -A1 $msgId` where `$filter` is the notmuch search query and `$msgId` the previous msg id that was still being logged. Then I did `notmuch show id:…` for the message following the one I did grep for. In the very top of the output you should be able to see if where notmuch thinks that file resides on disk.

```
$ afew --tag --new
Traceback (most recent call last):
  File "/nix/store/wzlksgjkx0nlrw7vyjkgn09nz681m9lw-afew-2.0.0/bin/.afew-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/wzlksgjkx0nlrw7vyjkgn09nz681m9lw-afew-2.0.0/lib/python3.7/site-packages/afew/commands.py", line 160, in main
    inner_main(args, database, query_string)
  File "/nix/store/wzlksgjkx0nlrw7vyjkgn09nz681m9lw-afew-2.0.0/lib/python3.7/site-packages/afew/main.py", line 23, in main
    filter_.run(query_string)
  File "/nix/store/wzlksgjkx0nlrw7vyjkgn09nz681m9lw-afew-2.0.0/lib/python3.7/site-packages/afew/filters/BaseFilter.py", line 60, in run
    self.handle_message(message)
  File "/nix/store/wzlksgjkx0nlrw7vyjkgn09nz681m9lw-afew-2.0.0/lib/python3.7/site-packages/afew/filters/HeaderMatchingFilter.py", line 28, in handle_message
    value = message.get_header(self.header)
  File "/nix/store/5zrq1c1gmq3fqpfr4cwslh404cgxraq2-python3.7-python-notmuch-0.29.2/lib/python3.7/site-packages/notmuch/message.py", line 265, in get_header
    raise NullPointerError()
notmuch.errors.NullPointerError

```

**Comment by GuillaumeSeren** [comment]
Hello @bjesus @andir sorry to be late,
I did not succeed to reproduce the issue on master (f581330),
on my setup, please give me more information on the use case.

**Comment by russell** [comment]
I hit the same error, in my case it was caused by not running `notmuch new` before running afew.  It looks like if the mail is missing, it will also error.

**Comment by GuillaumeSeren** [comment]
> I hit the same error, in my case it was caused by not running `notmuch new` before running afew. It looks like if the mail is missing, it will also error.

If you are out of sync between your maildir and notmuch the error is exepected.
