### ISSUE TITLE
DKIMValidityFilter crashes

### ISSUE THREAD

**Issue by mkgvt** [afewmail/afew#263]
[afew 2.0.0]

I inserted DKIMValidityFilter into the chain. Afew unexpectedly crashed on a dry run of my mail. It looks like no DNS server responded which is odd because it responds from the command line:
```
$ dig -t txt dk1024-2012._domainkey.engage.vmware.com

; <<>> DiG 9.14.9 <<>> -t txt dk1024-2012._domainkey.engage.vmware.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55598
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: ed80d888d7e6a6e4fc2276105e9487829dd3cee0b72f6c1b (good)
;; QUESTION SECTION:
;dk1024-2012._domainkey.engage.vmware.com. IN TXT

;; ANSWER SECTION:
dk1024-2012._domainkey.engage.vmware.com. 3600 IN TXT "v=DKIM1;" "p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC1TaNgLlSyQMNWVLNLvyY/neDgaL2oqQE8T5illKqCgDtFHc8eHVAU+nlcaGmrKmDMw9dbgiGk1ocgZ56NR4ycfUHwQhvQPMUZw0cveel/8EAGoi/UyPmqfcPibytH81NFtTMAxUeM4Op8A6iHkvAMj5qLf4YRNsTkKAVmJ5jEZwIDAQAB;"

;; Query time: 15 msec
;; SERVER: 198.82.247.66#53(198.82.247.66)
;; WHEN: Mon Apr 13 11:38:42 EDT 2020
;; MSG SIZE  rcvd: 338
```

Here is the traceback (on NixOS 19.09):
```
DEBUG:dkimpy:sig: {b'v': b'1', b'a': b'rsa-sha256', b'c': b'relaxed/relaxed', b's': b'dk1024-2012', b'd': b'engage.vmware.com', b'h': b'Message-ID:List-Unsubscribe:MIME-Version:From:To:Reply-To:Date:Subject:\r\n Content-Type', b'i': b'vmwareteam@engage.vmware.com', b'bh': b'0VxUCX2CqiU7uAwWiAZqWGHDvnYofDA+7ISD/j53iCA=', b'b': b'GIZ98rUkY37EwJ+3jPlsFwSFz0tgurUJH2VGzV2HVYqkfwxPX2eXa/IVxiJkwfks6nerGKqzkC0r\r\n   aBxMOcwyAAnPf+RTNKk7QmnX5kQlnwFjdrntj5KA8kxavb6ABcDzUzA66qBAZ7r9M+4hwo6N7R7s\r\n   q1mqkoYTJsxOqkC8gts='}
Traceback (most recent call last):
  File "/nix/store/7axc6gpph1fnjrwf02q6j4alh66m5n3i-afew-2.0.0/bin/.afew-wrapped", line 11, in <module>
    sys.exit(main())
  File "/nix/store/7axc6gpph1fnjrwf02q6j4alh66m5n3i-afew-2.0.0/lib/python3.7/site-packages/afew/commands.py", line 160, in main
    inner_main(args, database, query_string)
  File "/nix/store/7axc6gpph1fnjrwf02q6j4alh66m5n3i-afew-2.0.0/lib/python3.7/site-packages/afew/main.py", line 23, in main
    filter_.run(query_string)
  File "/nix/store/7axc6gpph1fnjrwf02q6j4alh66m5n3i-afew-2.0.0/lib/python3.7/site-packages/afew/filters/BaseFilter.py", line 60, in run
    self.handle_message(message)
  File "/nix/store/7axc6gpph1fnjrwf02q6j4alh66m5n3i-afew-2.0.0/lib/python3.7/site-packages/afew/filters/DKIMValidityFilter.py", line 38, in handle_message
    dkim_ok = all(map(verify_dkim, message.get_filenames()))
  File "/nix/store/7axc6gpph1fnjrwf02q6j4alh66m5n3i-afew-2.0.0/lib/python3.7/site-packages/afew/filters/DKIMValidityFilter.py", line 22, in verify_dkim
    return dkim.verify(message_bytes)
  File "/nix/store/pglvrcim2hqbf9l8fpvfab71wvpyjn7s-python3.7-dkimpy-0.9.2/lib/python3.7/site-packages/dkim/__init__.py", line 1266, in verify
    return d.verify(dnsfunc=dnsfunc)
  File "/nix/store/pglvrcim2hqbf9l8fpvfab71wvpyjn7s-python3.7-dkimpy-0.9.2/lib/python3.7/site-packages/dkim/__init__.py", line 869, in verify
    return self.verify_sig(sig, include_headers, sigheaders[idx], dnsfunc)
  File "/nix/store/pglvrcim2hqbf9l8fpvfab71wvpyjn7s-python3.7-dkimpy-0.9.2/lib/python3.7/site-packages/dkim/__init__.py", line 664, in verify_sig
    pk, self.keysize, ktag = load_pk_from_dns(name, dnsfunc)
  File "/nix/store/pglvrcim2hqbf9l8fpvfab71wvpyjn7s-python3.7-dkimpy-0.9.2/lib/python3.7/site-packages/dkim/__init__.py", line 423, in load_pk_from_dns
    s = dnsfunc(name)
  File "/nix/store/pglvrcim2hqbf9l8fpvfab71wvpyjn7s-python3.7-dkimpy-0.9.2/lib/python3.7/site-packages/dkim/dnsplug.py", line 85, in get_txt
    txt = _get_txt(unicode_name)
  File "/nix/store/pglvrcim2hqbf9l8fpvfab71wvpyjn7s-python3.7-dkimpy-0.9.2/lib/python3.7/site-packages/dkim/dnsplug.py", line 31, in get_txt_dnspython
    a = dns.resolver.query(name, dns.rdatatype.TXT,raise_on_no_answer=False)
  File "/nix/store/r40vvpd265ijvrzyac6pcq34qz68q185-python3.7-dnspython-1.16.0/lib/python3.7/site-packages/dns/resolver.py", line 1102, in query
    lifetime)
  File "/nix/store/r40vvpd265ijvrzyac6pcq34qz68q185-python3.7-dnspython-1.16.0/lib/python3.7/site-packages/dns/resolver.py", line 898, in query
    raise NoNameservers(request=request, errors=errors)
dns.resolver.NoNameservers: All nameservers failed to answer the query dk1024-2012._domainkey.engage.vmware.com. IN TXT: Server 198.82.247.66 UDP port 53 answered SERVFAIL; Server 198.82.247.34 UDP port 53 answered SERVFAIL
```

**Comment by GuillaumeSeren** [comment]
Hello @mkgvt thank you for the report,
I was using this filter, so I tested it on my setup seem's to reproduce.

As it is mostly external code dnspython / dkimpy I am checking if there is any issue on that.

**Comment by GuillaumeSeren** [comment]
Maybe @aidecoe who created this filter, have some info on this issue ?

**Comment by aidecoe** [comment]
@mkgvt so if dig resolves it, have you retried run with afew?

Although the exceptions in DKIM or DMARC aren't handled, so that is to fix anyway. See the PR #264. That's very quick fix, haven't got time to test it myself, yet. @mkgvt would you dare to give it a go?

**Comment by GuillaumeSeren** [comment]
Oh thank you for the quick patch @aidecoe,
I will test and reply on the PR.
