### ISSUE TITLE
catch NullPointerError in case mail file doesn't exist?

### ISSUE THREAD

**Issue by pazz** [afewmail/afew#43]
```
[~] afew -t -a                                                              1 ↵  
Error opening /home/pazz/mail//home/pazz/Maildir/Sent/new/1345574901.M170094P32649Q1.brick:2,S: No such file or directory
Traceback (most recent call last):
  File "/home/pazz/.local/bin/afew", line 189, in <module>
    main(options, query_string)
  File "/home/pazz/.local/lib/python2.7/site-packages/afew/main.py", line 33, in main
    filter_.run(query_string)
  File "/home/pazz/.local/lib/python2.7/site-packages/afew/Filter.py", line 61, in run
    self.handle_message(message)
  File "/home/pazz/.local/lib/python2.7/site-packages/afew/filters/SpamFilter.py", line 32, in handle_message
    if message.get_header('X-Spam-Flag') == 'YES':
  File "/home/pazz/.local/lib/python2.7/site-packages/notmuch/message.py", line 233, in get_header
    raise NullPointerError()
notmuch.errors.NullPointerError

```

**Comment by frankqux** [comment]
I too am getting this using `notmuch 0.19+103~g294bb6d`
```python
Traceback (most recent call last):
  File "/home/frankqux/.local/bin/afew", line 9, in <module>
    load_entry_point('afew==0.0.0', 'console_scripts', 'afew')()
  File "/home/frankqux/.local/lib/python2.7/site-packages/afew-0.0.0-py2.7.egg/afew/commands.py", line 205, in main
    inner_main(options, database, query_string)
  File "/home/frankqux/.local/lib/python2.7/site-packages/afew-0.0.0-py2.7.egg/afew/main.py", line 38, in main
    filter_.run(query_string)
  File "/home/frankqux/.local/lib/python2.7/site-packages/afew-0.0.0-py2.7.egg/afew/filters/BaseFilter.py", line 73, in run
    self.handle_message(message)
  File "/home/frankqux/.local/lib/python2.7/site-packages/afew-0.0.0-py2.7.egg/afew/filters/HeaderMatchingFilter.py", line 41, in handle_message
    value = message.get_header(self.header)
  File "/usr/local/lib/python2.7/dist-packages/notmuch/message.py", line 233, in get_header
    raise NullPointerError()
notmuch.errors.NullPointerError
```
Also, is this not the same as ~~#35~~ ?

**Comment by varac** [comment]
I'm getting this too just now, using few 1.3.0 and notmuch 0.25.1:

```
» afew --tag --new --verbose --verbose
Traceback (most recent call last):
  File "/home/varac/.local/bin/afew", line 11, in <module>
    load_entry_point('afew==1.3.0', 'console_scripts', 'afew')()
  File "/home/varac/.local/lib/python2.7/site-packages/afew-1.3.0-py2.7.egg/afew/commands.py", line 159, in main
    inner_main(args, database, query_string)
  File "/home/varac/.local/lib/python2.7/site-packages/afew-1.3.0-py2.7.egg/afew/main.py", line 23, in main
    filter_.run(query_string)
  File "/home/varac/.local/lib/python2.7/site-packages/afew-1.3.0-py2.7.egg/afew/filters/BaseFilter.py", line 60, in run
    self.handle_message(message)
  File "/home/varac/.local/lib/python2.7/site-packages/afew-1.3.0-py2.7.egg/afew/filters/HeaderMatchingFilter.py", line 28, in handle_message
    value = message.get_header(self.header)
  File "/usr/lib/python2.7/dist-packages/notmuch/message.py", line 233, in get_header
    raise NullPointerError()
notmuch.errors.NullPointerError
```

Unfortunatly I can't debug further b/c afew doesn't even tell my which mail it chokes on. Adding more `--verbose`` flags doesn't increase the verbosity.

**Comment by varac** [comment]
Same after upgrading to notmuch 0.26 and also after downgrading afew to 1.2.0 :o

**Comment by GuillaumeSeren** [comment]
@varac looks the same issue but I am not sure it is the best to dig up such an old issue (2012),
anyway as it seems to be related to your notmuch database when you run afew.

Can you reproduce the bug with older version of afew ?

**Comment by agrudzinsky** [comment]
For me, the error happens only when running the [ListMailsFilter].  It seems to die when processing a specific email, but I can't tell which one and why.  If I comment [ListMailsFilter] in the configuration file, the error does not occur.

`:!afew --tag --all -v                                                                                                                                                 
INFO:afew.filters.KillThreadsFilter.KillThreadsFilter:Looking for messages in killed threads that are not yet killed
INFO:afew.filters.ArchiveSentMailsFilter.ArchiveSentMailsFilter:Archiving all mails sent by myself to others
INFO:afew.filters.ArchiveSentMailsFilter.ArchiveSentMailsFilter:Committing changes to 5289 messages
INFO:afew.filters.ListMailsFilter.ListMailsFilter:Tagging mailing list posts
Traceback (most recent call last):
  File "/usr/bin/afew", line 11, in <module>
    load_entry_point('afew==1.3.0', 'console_scripts', 'afew')()
  File "/usr/lib/python3.7/site-packages/afew/commands.py", line 159, in main
    inner_main(args, database, query_string)
  File "/usr/lib/python3.7/site-packages/afew/main.py", line 23, in main
    filter_.run(query_string)
  File "/usr/lib/python3.7/site-packages/afew/filters/BaseFilter.py", line 60, in run
    self.handle_message(message)
  File "/usr/lib/python3.7/site-packages/afew/filters/HeaderMatchingFilter.py", line 28, in handle_message
    value = message.get_header(self.header)
  File "/usr/lib/python3.7/site-packages/notmuch/message.py", line 265, in get_header
    raise NullPointerError()
notmuch.errors.NullPointerError

shell returned 1
`
